/**
 * echarts 基本主题配置，减少使用时需要配置过多参数
 */
export default {
  version: 1,
  themeName: 'echart-zj',
  theme: {
    seriesCnt: '4',
    backgroundColor: 'rgba(0, 0, 0, 0)',
    titleColor: '#333',
    subtitleColor: '#999999',
    textColorShow: false,
    textColor: '#333',
    markTextColor: '#333333',
    color: [
      '#ff5614', // 高风险
      '#ffbe38', // 中高风险
      '#3ac2cf', // 中风险
      '#6ea0f9', // 低风险
      '#0092ff', // 渐进色开始色
      '#75d0f1', // 渐进色结束色
    ],
    borderColor: '#eeeeee',
    borderWidth: 0,
    visualMapColor: [
      '#0092ff',
      '#55aeff',
      '#eaf0f8',
    ],
    legendTextColor: '#333',
    kColor: '#ff5614',
    kColor0: '#6ea0f9',
    kBorderColor: '#ff5614',
    kBorderColor0: '#6ea0f9',
    kBorderWidth: 1,
    lineWidth: '2',
    symbolSize: '6',
    symbol: 'emptyCircle',
    symbolBorderWidth: '2',
    lineSmooth: true,
    graphLineWidth: 1,
    graphLineColor: '#aaa',
    mapLabelColor: '#999999',
    mapLabelColorE: '#ffffff',
    mapBorderColor: '#ffffff',
    mapBorderColorE: 'transparent',
    mapBorderWidth: 0.5,
    mapBorderWidthE: 1,
    mapAreaColor: '#eaf0f8',
    mapAreaColorE: '#0092ff',
    axes: [
      {
        type: 'all',
        name: '通用坐标轴',
        axisLineShow: true,
        axisLineColor: '#333',
        axisTickShow: true,
        axisTickColor: '#333',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: [
          '#ccc',
        ],
        splitAreaShow: false,
        splitAreaColor: [
          'rgba(250,250,250,0.3)',
          'rgba(200,200,200,0.3)',
        ],
      },
      {
        type: 'category',
        name: '类目坐标轴',
        axisLineShow: true,
        axisLineColor: '#d9d9d9',
        axisTickShow: true,
        axisTickColor: '#d9d9d9',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: false,
        splitLineColor: [
          '#ccc',
        ],
        splitAreaShow: false,
        splitAreaColor: [
          'rgba(250,250,250,0.3)',
          'rgba(200,200,200,0.3)',
        ],
      },
      {
        type: 'value',
        name: '数值坐标轴',
        axisLineShow: true,
        axisLineColor: '#d9d9d9',
        axisTickShow: true,
        axisTickColor: '#d9d9d9',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: [
          '#e8e8e8',
        ],
        splitAreaShow: false,
        splitAreaColor: [
          'rgba(250,250,250,0.3)',
          'rgba(200,200,200,0.3)',
        ],
      },
      {
        type: 'log',
        name: '对数坐标轴',
        axisLineShow: true,
        axisLineColor: '#d9d9d9',
        axisTickShow: true,
        axisTickColor: '#d9d9d9',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: [
          '#e8e8e8',
        ],
        splitAreaShow: false,
        splitAreaColor: [
          'rgba(250,250,250,0.3)',
          'rgba(200,200,200,0.3)',
        ],
      },
      {
        type: 'time',
        name: '时间坐标轴',
        axisLineShow: true,
        axisLineColor: '#d9d9d9',
        axisTickShow: true,
        axisTickColor: '#d9d9d9',
        axisLabelShow: true,
        axisLabelColor: '#333',
        splitLineShow: true,
        splitLineColor: [
          '#e8e8e8',
        ],
        splitAreaShow: false,
        splitAreaColor: [
          'rgba(250,250,250,0.3)',
          'rgba(200,200,200,0.3)',
        ],
      },
    ],
    axisSeperateSetting: true,
    toolboxColor: '#999',
    toolboxEmpasisColor: '#666',
    tooltipAxisColor: '#999999',
    tooltipAxisWidth: 1,
    timelineLineColor: '#293c55',
    timelineLineWidth: 1,
    timelineItemColor: '#293c55',
    timelineItemColorE: '#a9334c',
    timelineCheckColor: '#e43c59',
    timelineCheckBorderColor: 'rgba(194,53,49, 0.5)',
    timelineItemBorderWidth: 1,
    timelineControlColor: '#293c55',
    timelineControlBorderColor: '#293c55',
    timelineControlBorderWidth: 0.5,
    timelineLabelColor: '#293c55',
    datazoomBackgroundColor: 'rgba(47,69,84,0)',
    datazoomDataColor: 'rgba(47,69,84,0.3)',
    datazoomFillColor: 'rgba(167,183,204,0.4)',
    datazoomHandleColor: '#a7b7cc',
    datazoomHandleWidth: '100',
    datazoomLabelColor: '#333',
  },
};
